spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        use_sql_comments: false
        format_sql: true
        connection:
          autocommit: false
        cache:
          region_prefix: hibernate
          use_second_level_cache: false
          use_query_cache: false
          use_structured_entries: false
          region:
            factory_class: cloud.agileframework.cache.support.redis.RedisRegionFactory
